const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_INPUT: "INVALID_INPUT",

  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  TOKEN_SIGN_ERROR: "TOKEN_SIGN_ERROR",
  TOKEN_VERIFY_ERROR: "TOKEN_VERIFY_ERROR",
  PASSWORD_HASH_FAILED: "PASSWORD_HASH_FAILED",
  PASSWORD_COMPARE_FAILED: "PASSWORD_COMPARE_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_TOKEN: "INVALID_TOKEN",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  AUTHORIZATION_REQUIRED: "AUTHORIZATION_REQUIRED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  OWNERSHIP_REQUIRED: "OWNERSHIP_REQUIRED",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  HERD_NOT_FOUND: "HERD_NOT_FOUND",
  POST_NOT_FOUND: "POST_NOT_FOUND",
  COMMENT_NOT_FOUND: "COMMENT_NOT_FOUND",

  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  HERD_SLUG_ALREADY_EXISTS: "HERD_SLUG_ALREADY_EXISTS",

  DOMAIN_RULE_VIOLATION: "DOMAIN_RULE_VIOLATION",
  SELF_FOLLOW_NOT_ALLOWED: "SELF_FOLLOW_NOT_ALLOWED",
  DUPLICATE_VOTE_NOT_ALLOWED: "DUPLICATE_VOTE_NOT_ALLOWED",
  PRIVATE_HERD_ACCESS_DENIED: "PRIVATE_HERD_ACCESS_DENIED",
  MEMBERSHIP_REQUIRED: "MEMBERSHIP_REQUIRED",

  // Infrastructure Errors
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
  DATABASE_WRITE_ERROR: "DATABASE_WRITE_ERROR",
  DATABASE_READ_ERROR: "DATABASE_READ_ERROR",


  MEDIA_STORAGE_ERROR: "MEDIA_STORAGE_ERROR",
  MEDIA_UPLOAD_ERROR: "MEDIA_UPLOAD_ERROR",
  MEDIA_DELETE_ERROR: "MEDIA_DELETE_ERROR",

  EMAIL_DELIVERY_ERROR: "EMAIL_DELIVERY_ERROR",
  EMAIL_PROVIDER_ERROR: "EMAIL_PROVIDER_ERROR",

  INTERNAL_SERVICE_FAILED: "INTERNAL_SERVICE_FAILED",

  // System Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  STARTUP_FAILED: "STARTUP_FAILED",
};

export default ErrorCodes;
