const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",

  AUTHORIZATION_REQUIRED: "AUTHORIZATION_REQUIRED",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};

export default ErrorCodes;
